#if !canImport(ObjectiveC)
import XCTest

extension VersionCommandTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__VersionCommandTests = [
        ("testVersion", testVersion),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(VersionCommandTests.__allTests__VersionCommandTests),
    ]
}
#endif
