#if !canImport(ObjectiveC)
import XCTest

extension HelpCommandTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__HelpCommandTests = [
        ("testHelp", testHelp),
    ]
}

extension PackageCommandTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PackageCommandTests = [
        ("testCommand", testCommand),
    ]
}

extension VersionCommandTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__VersionCommandTests = [
        ("testVersion", testVersion),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(HelpCommandTests.__allTests__HelpCommandTests),
        testCase(PackageCommandTests.__allTests__PackageCommandTests),
        testCase(VersionCommandTests.__allTests__VersionCommandTests),
    ]
}
#endif
