import Foundation
import XCTest
@testable import SourceDocsLib

class DocumentationGeneratorTests: XCTestCase {
    func testFooter() {
        let footer = DocumentationGenerator.generateFooter(reproducibleDocs: true)
        XCTAssertEqual(
            footer,
            """
            This file was generated by [SourceDocs](https://github.com/eneko/SourceDocs)
            """
        )
    }
}
