#if !canImport(ObjectiveC)
import XCTest

extension AccessLevelTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AccessLevelTests = [
        ("testAccessibilityKey", testAccessibilityKey),
        ("testLevels", testLevels),
        ("testOrdering", testOrdering),
    ]
}

extension FilenameTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FilenameTests = [
        ("testMethodFilename", testMethodFilename),
    ]
}

extension MarkdownIndexTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MarkdownIndexTests = [
        ("testFooter", testFooter),
    ]
}

extension SourceDocsErrorTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SourceDocsErrorTests = [
        ("testErrorMessage", testErrorMessage),
    ]
}

extension SwiftDocDictionaryTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SwiftDocDictionaryTests = [
        ("testCollectionOutput", testCollectionOutput),
        ("testComment", testComment),
        ("testDeclaration", testDeclaration),
        ("testEmptyCollectionOutput", testEmptyCollectionOutput),
        ("testIsKind", testIsKind),
        ("testIsNotKind", testIsNotKind),
        ("testIsNotOneOf", testIsNotOneOf),
        ("testIsOneOf", testIsOneOf),
        ("testNestedType", testNestedType),
        ("testNoComment", testNoComment),
        ("testNoDeclaration", testNoDeclaration),
        ("testNoName", testNoName),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(AccessLevelTests.__allTests__AccessLevelTests),
        testCase(FilenameTests.__allTests__FilenameTests),
        testCase(MarkdownIndexTests.__allTests__MarkdownIndexTests),
        testCase(SourceDocsErrorTests.__allTests__SourceDocsErrorTests),
        testCase(SwiftDocDictionaryTests.__allTests__SwiftDocDictionaryTests),
    ]
}
#endif
