#if !canImport(ObjectiveC)
import XCTest

extension AccessLevelTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AccessLevelTests = [
        ("testAccessibilityKey", testAccessibilityKey),
        ("testLevels", testLevels),
        ("testOrdering", testOrdering)
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(AccessLevelTests.__allTests__AccessLevelTests)
    ]
}
#endif
