name: Install SourceDocs

on: [push, pull_request]

jobs:
  homebrew:
    name: Install with Homebrew
    runs-on: macos-latest
    steps:
    - name: Install
      run: |
        brew install sourcedocs
        sourcedocs version

  from-source:
    name: Install from Source
    runs-on:
    - macos-latest
    - ubuntu-latest
    steps:
    - name: Install
      run: |
        git clone --depth 1 https://github.com/eneko/SourceDocs.git
        cd SourceDocs
        make install
        sourcedocs version
